# The URL the site will be built for

# this variable has to be set but it is not used
# inside the templates (end in '/')
base_url = "https://noresmhub.github.io/NorESM2_Workshop_2024/"

# When adapting the title, do not forget to also adjust base_url above
title = "NorESM2 user workshop 2024"
description = "An introductory course on how to set up, run and diagnose NorESM2."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "cheerfully-light"

# Whether external links are to be opened in a new tab
external_links_target_blank = true

[extra]

navigation = []
# navigation = [
#     { name = "About", target = "" },
#     { name = "List of exercises", target = "exercises/" },
#     { name = "Audience", target = "audience/" },
#     #{ name = "Certificates", target = "certificates/" },
#     { name = "How to join", target = "join/" },
#     { name = "Requirements", target = "requirements/" },
#     #{ name = "Q&A", target = "questions/" },
#     #{ name = "Code of conduct", target = "code-of-conduct/" },
#     { name = "Communication", target = "communication/" }
# ]

# # twitter_image = "https://raw.githubusercontent.com/coderefinery/coderefinery-artwork/main/socialshare/socialshare-workshop.png"

# plausible.io analytics
#plausible = { src = "https://plausible.cs.aalto.fi/js/script.js", domain = "coderefinery.github.io", github_ref = "refs/heads/main" }


# you can place multiple logos like this
# the image file(s) need to be placed in content/logos
logos = [
#   { alt_text = "CodeRefinery logo", target_url = "https://coderefinery.org/", image = "coderefinery.png" },
#   { alt_text = "CodeRefinery logo", target_url = "https://coderefinery.org/", image = "coderefinery.png" }
    { alt_text = "INES logo", target_url = "https://www.noresm.org/", image = "ines.png" }
]

# adapt this
registration_link = "https://docs.google.com/forms/d/e/1FAIpQLScbJNH4IiA6VYm7HEt7zQCIHkGcO0dHkO14VcxFMqa77w0ANw/viewform?usp=sf_link"
source_repo = "https://github.com/NorESMhub/NorESM2_Workshop_2024"
#how_to_join_video = "https://youtu.be/QUAZELOioUY"

# uncomment as soon as registration opens
# registration_is_open = true

# uncomment as soon as registration closes
registration_is_closed = true
